In [6]:
# class MCMC_Sampler(Sampler):
#     def __init__(self, SUR_data) -> None:
#         super().__init__(SUR_data)

#     def sample(self):
#         pass

In [39]:
from utils import generate_SUR, Sampler, DefaultParams
import numpy as np
from numpy.linalg import inv
from scipy.stats import invwishart, invgamma

In [46]:
params = DefaultParams()
data = generate_SUR()

In [47]:
omega_inv = inv(params.omega)
omega_inv_tensor = np.block([
                [omega_inv[0,0]*np.eye(params.n), omega_inv[0,1]*np.eye(params.n)],
                [omega_inv[1,0]*np.eye(params.n), omega_inv[1,1]*np.eye(params.n)],
])

In [48]:
X = data['X']
Y = data['Y']
y1 = Y[:100]
y2 = Y[100:]
x1 = data['x1']
x2 = data['x2']
X_transposed = np.transpose(X)

In [49]:
beta_hat = inv(X_transposed @ omega_inv_tensor @ X) @ X_transposed @ omega_inv_tensor @ Y
omega_hat = inv(X_transposed @ omega_inv_tensor @ X)

In [50]:
m1 = y1 - x1 @ params.beta1
m2 = y2 - x2 @ params.beta2
R = np.array([[(np.transpose(m1) @ m1).item() , (np.transpose(m1) @ m2).item()],
              [(np.transpose(m2) @ m1).item() , (np.transpose(m2) @ m2).item()],])

In [52]:
R

array([[ 11.7548241 ,  -9.42084244],
       [ -9.42084244, 128.67311482]])

In [37]:
np.random.multivariate_normal(mean=beta_hat.reshape(-1,), cov=omega_hat)

array([ 3.0091081 , -1.99050284,  1.9944703 ,  1.01579687])

In [57]:
invwishart.rvs(df=params.n, scale=R)

array([[ 0.10882734, -0.13758811],
       [-0.13758811,  1.19858282]])